# Generated by Django 3.2.5 on 2021-09-11 01:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [

        ('repository', '0002_auto_20210903_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='标签名')),
                ('c_day', models.DateField(auto_now_add=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AlterModelOptions(
            name='businessunit',
            options={'verbose_name': '业务线', 'verbose_name_plural': '业务线'},
        ),
        migrations.AlterModelOptions(
            name='idc',
            options={'verbose_name': '机房', 'verbose_name_plural': '机房'},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'verbose_name': '服务器表', 'verbose_name_plural': '服务器表'},
        ),
        migrations.RemoveField(
            model_name='idc',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='server',
            name='business_unit',
        ),
        migrations.RemoveField(
            model_name='server',
            name='cabinet_num',
        ),
        migrations.RemoveField(
            model_name='server',
            name='cabinet_order',
        ),
        migrations.RemoveField(
            model_name='server',
            name='device_status_id',
        ),
        migrations.AddField(
            model_name='businessunit',
            name='memo',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='businessunit',
            name='parent_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_level', to='repository.businessunit'),
        ),
        migrations.AddField(
            model_name='idc',
            name='memo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='server',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin', to='login.user', verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='server',
            name='asset_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, unique=True, verbose_name='资产名称'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='created_by',
            field=models.CharField(choices=[('auto', '自动添加'), ('manual', '手工录入')], default='auto', max_length=32, verbose_name='添加方式'),
        ),
        migrations.AddField(
            model_name='server',
            name='memo',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '在线'), (1, '下线'), (2, '未知'), (3, '故障'), (4, '备用')], default=0, verbose_name='设备状态'),
        ),
        migrations.AddField(
            model_name='server',
            name='sub_asset_type',
            field=models.SmallIntegerField(choices=[(0, 'PC服务器'), (1, '刀片机'), (2, '小型机')], default=0, verbose_name='服务器类型'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='机房名称'),
        ),
        migrations.AlterField(
            model_name='server',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.idc', verbose_name='所在机房'),
        ),
        migrations.AddField(
            model_name='server',
            name='tags',
            field=models.ManyToManyField(blank=True, to='repository.Tag', verbose_name='标签'),
        ),
    ]
