# Generated by Django 3.2.5 on 2021-09-11 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20210911_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.businessunit', verbose_name='所属业务线'),
        ),
    ]
