# Generated by Django 3.2.5 on 2021-09-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_alter_tag_c_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='sub_asset_type',
        ),
    ]
