# Generated by Django 3.2.5 on 2021-09-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_remove_server_sub_asset_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessunit',
            name='parent_unit',
        ),
    ]
