# Generated by Django 3.2.5 on 2021-09-15 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_remove_businessunit_parent_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ErrorLog',
        ),
    ]
