# Generated by Django 3.2.5 on 2021-09-15 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_delete_errorlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='server',
            options={'ordering': ['-latest_date'], 'verbose_name': '服务器表', 'verbose_name_plural': '服务器表'},
        ),
    ]
