# Generated by Django 3.2.5 on 2021-09-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0010_alter_server_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='admin',
        ),
    ]
