# Generated by Django 3.2.7 on 2022-01-15 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0013_remove_server_asset_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='tags',
        ),
        migrations.AddField(
            model_name='server',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='repository.tag', verbose_name='标签'),
        ),
    ]
