# Generated by Django 3.2.7 on 2022-01-15 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0014_auto_20220115_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
