# Generated by Django 3.2.5 on 2021-09-19 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webssh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminallog',
            old_name='cmd',
            new_name='cmdb',
        ),
    ]
