# Generated by Django 3.2.7 on 2021-11-03 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_loginlog_event_type'),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128, verbose_name='组名')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '主机组',
                'verbose_name_plural': '主机组',
                'ordering': ['-create_time'],
                'unique_together': {('group_name', 'user')},
            },
        ),
    ]
